version: "3.7"
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./config/nginx:/etc/nginx/conf.d:ro
      - static:/static
      - media:/media/meetandeat
    depends_on:
      - web
    restart: on-failure
  certbot:
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  web:
    build: .
    container_name: dg01
    depends_on:
      - db
    volumes:
      - ./meeteat:/meeteat
      - static:/static
      - media:/media/meetandeat
    expose:
      - "8000"
    restart: always

  db:
    image: postgres:latest
    container_name: ps01
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=meet_and_eat
    restart: on-failure

volumes:
    static:
    media:
  
