version: "2.3"
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - meeteat:/meeteat
      - ./config/nginx:/etc/nginx/conf.d
      - static:/static
      - media:/media/meetandeat
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    depends_on:
      - db
    volumes:
      - meeteat:/meeteat
      - static:/static
      - media:/media/meetandeat
    ports:
      - "8000:8000"
    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: ps01
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=meet_and_eat

volumes:
    meeteat:
    static:
    media:
