version: "2"
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./meeteat:/meeteat
      - ./config/nginx:/etc/nginx/conf.d
      - ./meeteat/meetandeat/static:/static
      - /media/meetandeat
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    depends_on:
      - db
    volumes:
      - ./meeteat:/meeteat
      - ./meeteat/meetandeat/static:/static
      - /media/meetandeat
    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: ps01
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=meet_and_eat
