version: "3.7"
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d:ro
      - static:/static
      - media:/media/meetandeat
    depends_on:
      - web
    restart: on-failure
  web:
    build: .
    container_name: dg01
    depends_on:
      - db
    volumes:
      - ./meeteat:/meeteat
      - static:/static
      - media:/media/meetandeat
    expose:
      - "8000"
    restart: on-failure

  db:
    image: postgres:latest
    container_name: ps01
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=meet_and_eat
    restart: on-failure

volumes:
    static:
    media:
  
