# Generated by Django 2.2.1 on 2019-05-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetandeat', '0003_auto_20190527_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='participants',
            new_name='participants_number',
        ),
    ]
