# Generated by Django 2.1.5 on 2019-06-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetandeat', '0004_auto_20190528_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='visible',
        ),
    ]
