# Generated by Django 2.2 on 2019-05-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetandeat', '0004_auto_20190528_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='super_user',
        ),
    ]
