# Generated by Django 2.2 on 2019-06-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetandeat', '0005_auto_20190529_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='super_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='visible',
        ),
    ]
