# Generated by Django 2.1.5 on 2019-06-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetandeat', '0005_remove_user_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('approved', models.BooleanField(default=False)),
                ('events', models.ManyToManyField(to='meetandeat.Event')),
            ],
        ),
    ]
