# Generated by Django 2.2 on 2019-06-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetandeat', '0006_auto_20190606_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
